### PR TITLE
Overhaul to Procedural Macro

### PR DESCRIPTION
**Pull request by AdinAck**
I noticed you guys were having some problems in #10 and #8, I thought about it and realized an attribute macro would resolve these issues and honestly make the interface cleaner and less "magical" by grounding the resource groups in actual user-defined structs.

The refined example with the new attribute macro:
```rust
use embassy_stm32::peripherals::*;
use assign_resources::assigned_resources;

#[assigned_resources]
struct UsbResources {
    dp: PA12,
    dm: PA11,
    usb: USB,
}

#[assigned_resources]
struct LedResources {
    r: PA2,
    g: PA3,
    b: PA4,
    #[alias = PWMTimer] // make an alias for this resource
    tim2: TIM2,
}

#[embassy_executor::task]
async fn usb_task(r: UsbResources) {
    // use r.dp, r.dm, r.usb
}

async fn setup_leds<'a>(r: LedResources) -> SimplePWM<'a, PWMTimer> {
    // setup three channel PWM (one for each color)       ^ alias used here
}

#[embassy_executor::task]
async fn led_task(rgb_pwm: SimplePWM<'a, PWMTimer>) {
    // use rgb_pwm                       ^ alias used here
}

#[embassy_executor::main]
async fn main(spawner: embassy_executor::Spawner) {
    let p = embassy_stm32::init(Default::default());

    let rgb_pwm = setup_leds(led_resources!(p));

    spawner.spawn(usb_task(usb_resources!(p))).unwrap();
    spawner.spawn(led_task(rgb_pwm)).unwrap();

    // can still use p.PA0, p.PA1, etc
}
```

I also address the concerns of field-wise attributes and ambiguous typing in the new tests.

### CODE REVIEW

**Comment by adamgreig** [comment]
This is really interesting and does resolve some of the current problems. The syntax is nice too, but I'm not sure if I want a proc macro rather than sticking to a simple macro-by-example. Ultimately this is more or a less a total rewrite, so maybe it would make more sense as its own crate?

Incidentally, I really disagree with stuffing `.gitignore` full of platform- and editor-specific junk like `.DS_Store`; those things can and should be added to your own system's global ignore file instead of cluttering up every project. There's a few posts about how to do this like [1](https://sebastiandedeyne.com/setting-up-a-global-gitignore-file/) and [2](https://blog.martinhujer.cz/dont-put-idea-vscode-directories-to-projects-gitignore/). Plus, this generator's idea about `Cargo.lock` is not only wrongly applied here (this is a library after all) but probably [wrong in general now](https://blog.rust-lang.org/2023/08/29/committing-lockfiles.html).

**Comment by AdinAck** [comment]
> Incidentally, I really disagree with stuffing `.gitignore` full of platform- and editor-specific junk like `.DS_Store`; those things can and should be added to your own system's global ignore file instead of cluttering up every project. There's a few posts about how to do this like [1](https://sebastiandedeyne.com/setting-up-a-global-gitignore-file/) and [2](https://blog.martinhujer.cz/dont-put-idea-vscode-directories-to-projects-gitignore/). Plus, this generator's idea about `Cargo.lock` is not only wrongly applied here (this is a library after all) but probably [wrong in general now](https://blog.rust-lang.org/2023/08/29/committing-lockfiles.html).

Woops! That wasn't supposed to slip into this PR. I agree with you... in a perfect world. Unfortunately, I am a GUI pleb and use GitHub Desktop which often gets confused by *local* .gitignores. It ususally just disregards a global one.



> Ultimately this is more or a less a total rewrite, so maybe it would make more sense as its own crate?

Yeah lol it is, I didn't want to just rip off your idea and make a new crate. I basically wanted to propose this idea to you via this PR. Also, if I made a separate crate, it's a bit awkward having two things solve the same problem, and you've got the nice name `assign-resources` registered on crates.io. I can't think of any reason to use the `macro_rules!` implementation over the attribute macro (please tell me some, maybe I could improve the attribute macro) so I wanted to bring this to you so if you *wanted* to just update this crate with the attribute macro you could.

But if you believe a new crate is the way to go, I will oblige. I'll just have to come up with a clever new name, maybe `assigned-resources` or `resource-assignment`, we'll see!

**Comment by AdinAck** [comment]
Created a new crate with these changes [here](https://github.com/AdinAck/embedded-resources).

**Comment by spookyvision** [comment]
you can configure per-repo ignores that aren't commited to git by using an `exclude` file (typically `.git/info/exclude`) - more details in the [docs](https://git-scm.com/docs/gitignore)

**Pull request closed without merging**
